# Generated by Django 5.0.4 on 2024-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_indexmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField()),
                ('Email_Id', models.EmailField(max_length=50)),
                ('Doctor_name', models.EmailField(max_length=50)),
                ('Booking_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='usermsg',
            name='name',
            field=models.EmailField(max_length=50),
        ),
    ]
