# Generated by Django 5.0.4 on 2024-05-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_booking_alter_usermsg_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Booking_date',
            new_name='Bookingdate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Doctor_name',
            new_name='Doctorname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Email_Id',
            new_name='EmailId',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Patient_name',
            new_name='Patientname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Phone_number',
            new_name='Phonenumber',
        ),
    ]
