# Generated by Django 5.0.4 on 2024-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_booking_date_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctordata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('name', models.CharField(max_length=80)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
