# Generated by Django 5.0.4 on 2024-05-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.CharField(max_length=80),
        ),
    ]
