# Generated by Django 5.0.4 on 2024-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.URLField(),
        ),
    ]
