# Generated by Django 5.0.4 on 2024-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='gmail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
