# Generated by Django 5.0.4 on 2024-05-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_socialmedia_gmail_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socialmedia',
        ),
    ]
